Repository sk-prj-genai-question-app/ai-service, pull requests merged in 2025-07, with the labels that each got.

#17 [ENHANCE] 어휘 문제 생성 시 주제, 품사 다양성 개선
  app/problem_generator/rag_chain.py
  app/problem_generator/router.py
Labels: bug fix, enhancement

#20 [FEAT] 사용자 기반 문제 질문 AI 구분 구현
  app/main.py
  app/user_question_chatbot/chain.py
  app/user_question_chatbot/router.py
Labels: feature

#25 Enhan/API 키 변경
  app/user_question_chatbot/chain.py
Labels: enhancement
